### ISSUE TITLE
Make the default puppet at the beginning more human-like

### ISSUE THREAD

**Issue by Jigyasu** [una-dinosauria/image-annotator#10]
This will reduce the number of clicks on the first frame.

**Comment by umgupta** [comment]
The idea is this template can be used for all videos in which annotations is to be done. Now depending on video initial location will be different. Hence, I have put it in center so that it is generic to any video (for human annotation). So with that idea I am closing it for now. Open it if we still want to go ahead with this.

**Comment by umgupta** [comment]
Just to add, we have complete puppet dragging with center button for this very reason.
